
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: login_detector
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Login Page Analyzer Microservice
  analyzer-service:
    build:
      context: ./services/analyzer
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/login_detector
      - PORT=3001
    depends_on:
      - postgres

  # Form Storage Microservice
  form-service:
    build:
      context: ./services/forms
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/login_detector
      - PORT=3002
    depends_on:
      - postgres

  # Login Submission Microservice
  submitter-service:
    build:
      context: ./services/submitter
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3003:3003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/login_detector
      - PORT=3003
    depends_on:
      - postgres

  # API Gateway
  api-gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - ANALYZER_SERVICE_URL=http://analyzer-service:3001
      - FORM_SERVICE_URL=http://form-service:3002
      - SUBMITTER_SERVICE_URL=http://submitter-service:3003
      - PORT=3000
    depends_on:
      - analyzer-service
      - form-service
      - submitter-service

  # Frontend GUI
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5173:80"
    environment:
      - VITE_API_BASE_URL=http://api-gateway:3000
    depends_on:
      - api-gateway

volumes:
  postgres_data:
