// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbjldjsdkxibnmkxswjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iamxkanNka3hpYm5ta3hzd2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODIzNzYsImV4cCI6MjA2NTI1ODM3Nn0.TSPkKdMgD79grpkzQ6mnJP3fozp2MX5spJQ_VvrCb-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);